# Generated by Django 5.2.3 on 2025-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Aguardando Abertura"),
                    ("open", "Sessão Aberta"),
                    ("closed", "Votação Encerrada"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
    ]
