# Generated by Django 5.2.3 on 2025-06-28 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0002_topic_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="status",
        ),
    ]
