# Generated by Django 5.2.3 on 2025-06-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0004_alter_votingsession_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingsession",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="voting.topic",
            ),
        ),
    ]
